config/routes.rb
Rails.application.routes.draw do
 
  root to: "tests#index" 

  
  devise_for :users, controllers: { sessions: 'users/sessions' }, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout }

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index


  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passage, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member 
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
   MAX_ANSWERS_COUNT = 4

  belongs_to :question

  validates :body, presence: true
  #validate :answers_count, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def answers_count
    message = 'exceeded maximum number of answers to the question'
    errors.add(:question, message) if question.answers.count >= MAX_ANSWERS_COUNT
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  BADGES_TYPE = {
    'Прохождение всех тестов категории' => :all_category_tests,
    'Прохождение теста с первой попытки' => :test_first_try,
    'Прохождение всех тестов определнного уровня' => :all_level_tests
  }.freeze

  before_save :set_default_image_path, unless: :image_path?

  def self.images
    images_path = 'app/assets/images/'
    badges = Dir.glob("#{images_path}badges/*")
    badges.map { |badge_path| badge_path.gsub(images_path, '') }
  end

  has_many :users_badges
  has_many :users, through: :users_badges
  belongs_to :category, class_name: 'Category', optional: true

  validates :title, presence: true
  validates :assigment_rule, presence: true

  private

  def set_default_image_path
    self.image_path = 'badges/badge-default.png'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
   belongs_to :user
  belongs_to :question

  def hash
    url.split("/").last
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'
  has_many :questions
  has_many :test_passage
  has_many :user, through: :test_passage

  validates :title, presence: true, uniqueness: {
    scope: :level,
    message: 'there can be only one test with this title and difficulty level'
  }
  validates :level, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }

  scope :by_level, ->(level) { where(level: level) }
  scope :easy, -> { by_level(0..1) }
  scope :medium, -> { by_level(2..4) }
  scope :hard, -> { by_level(5..Float::INFINITY) }
  scope :by_category, ->(title) { joins(:category).where(categories: { title: title }) }

  def self.titles_by_category(title)
    by_category(title).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord 
  SUCCESS_PERSENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: %i[create update]

  def accept!(answer_ids)
    self.correct_answers += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end

  def correct_answers_percent
    (correct_answers.to_f / test.questions.count.to_f) * 100
  end

  def successfully_completed?
    correct_answers_percent >= SUCCESS_PERSENT
  end

  private

  def before_validation_set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers_count = true_answers.count

    (correct_answers_count == answer_ids.count) &&
      correct_answers_count == true_answers.where(id: answer_ids).count
  end

  def true_answers
    @true_answers ||= current_question.answers.correct
  end

  def next_question
    test.questions
        .order(:id)
        .where('id > ?', current_question.nil? ? 0 : current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :trackable
         
  has_many :test_passage
  has_many :test, through: :test_passage
  has_many :tests_author, class_name: 'Test', foreign_key: :author_id

  validates :email, presence: true 

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/users_badge.rb
class UsersBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: :start

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passing(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to "TestGuru", "https://github.com/#{author}/#{repo}", target: :blank
  end

  def flash_messages
    flash.map do |type, message|
      content_tag :p, message, class: "flash #{type}"
    end.join("\n").html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    header = question.new_record? ? 'Create New' : 'Edit'
    header << " #{question.test.title} Question"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_level(test)
    case test.level
    when 1 then t('difficulty_level.easy')
    when 2 then t('difficulty_level.medium')
    when 3 then t('difficulty_level.hard')
    else t('difficulty_level.hero')
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to t('.header'), root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item nav-link active">
        <%= link_to t('.gists'), admin_gists_path, class: 'nav-item nav-link' %>
        <%= link_to t('.badges'), admin_badges_path, class: 'nav-item nav-link' %>
      </li>
    </ul>
  </div>
  <span class="navbar-text">
    <%= t('.hello') %>,
    <b class="nav-admin user-email"><%= current_user.email %></b>
    <%= t('.guru') %>
    |
    <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
  </span>
</div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.header')%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/header' %>
    <div class="container">
      <%= flash_messages %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
    
    <title>Gura</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
      <div class="container">
        <%= flash_messages %>
        <%= yield %>
      </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
  <div>
    <h2><%= t('.header', count: resource.errors.count) %></h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
  <% end %>
<% end %>
  

app/views/shared/_footer.html.erb
<p>
  <%= current_year %> Sergey Maslov
</p>

<p>
  <%= github_url("jezman", "test_guru") %> is a testing platform where users can create, manage and pass tests.
</p>

<p>
  <%= link_to "Учебный проект в онлайн-школе Thinknetica", "https://thinknetica.com", target: :blank %>
</p> 

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "TestGuru", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

  <% if current_user && current_user.admin? %>
      <li class="nav-item active">
        <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
        <%= link_to t('admin.header.header'), admin_tests_path, class: 'navbar-link' %>
        <%= link_to t('.badges'), badges_path, class: 'nav-item nav-link' %>
      </li>
  <% end %>

    </ul>
  </div>
  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('.hello')%>,
      <b><%= current_user.email %></b>
      Guru |
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.signup'), new_user_registration_path %>
      |
      <%= link_to t('.login'), new_user_session_path %>
    <% end %>
  </span>
</nav>