config/routes.rb
Rails.application.routes.draw do
 
  root to: "tests#index" 

  
  devise_for :users, controllers: { sessions: 'users/sessions' }, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout }

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index


  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passage, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member 
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord 
  SUCCESS_PERSENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: %i[create update]

  def accept!(answer_ids)
    self.correct_answers += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end

  def correct_answers_percent
    (correct_answers.to_f / test.questions.count.to_f) * 100
  end

  def successfully_completed?
    correct_answers_percent >= SUCCESS_PERSENT
  end

  private

  def before_validation_set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers_count = true_answers.count

    (correct_answers_count == answer_ids.count) &&
      correct_answers_count == true_answers.where(id: answer_ids).count
  end

  def true_answers
    @true_answers ||= current_question.answers.correct
  end

  def next_question
    test.questions
        .order(:id)
        .where('id > ?', current_question.nil? ? 0 : current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      awarded_badges! if @test_passage.successfully_completed?

      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    service = GistQuestionService.new(@test_passage.current_question)
    response = service.call

    gist_url = response.html_url
    gist_link = view_context.link_to(gist_url, gist_url, target: :blank)

    flash_message = if service.status_ok?
                      create_gist!(gist_url)
                      { notice: t('.success', url: gist_link) }
                    else
                      { alert: t('.failed') }
                    end

    redirect_to @test_passage, flash_message

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def create_gist!(gist_url)
    current_user.gists.create(question: @test_passage.current_question, url: gist_url)
  end

  def awarded_badges!
    badge_service = BadgeService.new(@test_passage)
    badge_service.awarded_badges!
    current_user.badges.push(badge_service.badges)
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/_progress_bar.html.erb
<div class="progress">
  <% questions_count = @test_passing.test.questions.count %>
  <% current_question_number = @test_passing.current_question ? @test_passing.current_question_number : questions_count + 1 %>
  <%= content_tag :div,
                  '',
                  class: 'progress-bar bg-success',
                  role: 'progressbar',
                  data: { questions_count: questions_count,
                          current_question_number: current_question_number } %>
</div> 

app/views/test_passages/result.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <%= render 'progress_bar' %>
    <h1 class="<%= set_result_color(@test_passing) %>">
      <%= t('.header', title: @test_passing.test.title) %>
      <%= show_result_message(@test_passing)%></h1><br>
    <h2><%= link_to t('.back'), tests_path %></h2>
  </div>
</div>
 

app/views/test_passages/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h1><%= t('.header', test_title: @test_passage.test.title) %></h1>

    <%= render 'progress_bar' %>

    <div class="row">
      <dt class="col-sm-9">
        <%= t('.questions', current_question: @test_passage.current_question_number, questions_count: @test_passage.test.questions.count) %>
      </dt>
      <dd class="col-sm-3">
        <%= link_to 'Gist question', gist_test_passage_path(@test_passage), method: :post %>
      </dd>
    </div>

    <div class="card">
      <div class="card-header">
        <%= @test_passage.current_question.body%>
      </div>

      <ul class="list-group list-group-flush">
        <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
          <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
          <li class="list-group-item">
            <%= b.check_box id: "answer_ids_#{b.object.id}" %>
            <%= b.label %>
          </li>
         <% end %>

        </ul>
        <%= form.submit t('.next'), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>