config/routes.rb
Rails.application.routes.draw do
 
  root to: "tests#index" 

  
  devise_for :users, controllers: { sessions: 'users/sessions' }, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout }

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index


  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passage, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member 
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[create new]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def show; end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_test_path(@test), notice: t('admin.created', resource: @question.model_name.human)   
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test), notice: t('admin.updated', resource: @question.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    redirect_to admin_test_path(@question.test), notice: t('admin.deleted', resource: @question.model_name.human)
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end 

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[create new]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def show; end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to test_path(@test)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    redirect_to test_path(@question.test)
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    header = question.new_record? ? 'Create New' : 'Edit'
    header << " #{question.test.title} Question"
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :body %><br />
    <%= form.text_field :body, id: :question_body %>
  </p>

  <p><%= form.submit %></p>
<% end %> 

app/views/admin/questions/_question.html.erb
<% @test.questions.each do |question| %>
<tr>
  <td><%= question.body %></td>
  <td><%= link_to t('.show'), admin_question_path(question) %></td>
  <td><%= link_to t('.edit'), edit_admin_question_path(question) %></td>
  <td><%= link_to t('.delete'),
                  admin_question_path(question),
                  method: :delete,
                  data: { confirm: t('.delete_confirmation') } %>
  </td>
<% end %>
</tr> 

app/views/admin/questions/edit.html.erb
<h1><%= t('.header', test_title: @question.test.title) %></h1>
<%= render 'form' %>
<%= link_to t('.back'), admin_test_path(@question.test) %> 

app/views/admin/questions/new.html.erb
<h1><%= t('.header', test_title: @question.test.title) %></h1>
<%= render 'form' %>
<%= link_to t('.back'), admin_test_path(@question.test) %>

app/views/admin/questions/show.html.erb
<h1><%= t('.header', test_title: @question.test.title) %></h1>

<p><%= @question.body %></p>

<h2><%= t('.answers') %></h2>

<%= link_to t('.new_answer'), new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to t('.edit'), edit_admin_question_path(@question) %>
<%= link_to t('.back'), admin_test_path(@question.test) %>